apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabhub-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: collabhub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collabhub-backend
                port:
                  number: 5000
